version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - docker_elk

  kibana:
    container_name: kibana
    image: kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    command: --strict.perms=false
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

## logstash

  logstash:
    container_name: logstash
    image: logstash:7.17.9
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf:ro,Z
      - ./logstash/pipeline/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    command: logstash -f /usr/share/logstash/config/logstash.conf
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
   networks:
      - docker_elk
   depends_on:
      - elasticsearch
   restart: unless-stopped

## logstash

## nginx
  nginx:
    image: nginx:1.25
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
    networks:
      - docker_elk
    depends_on:
      - logstash
    restart: always
## nginx

networks:
  docker_elk:
    driver: bridge


volumes:
  elasticsearch-data:
    driver: local